language: php

branches:
  # Only test the master branch and semantic version tags.
  only:
    - master
    - /^[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+.*$/

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

sudo: false

env:
  global:
    - TERMINUS_TEST_MODE=1
    - COMPOSER_PROCESS_TIMEOUT=3600

before_script:
  - set -ex
  - composer install --no-interaction --prefer-dist

script:
  - composer clover
  - phpenv config-rm xdebug.ini # XDebug is needed for code coverage, but makes things slow. It's enabled by default in Travis, we disable it here post-coverage run for speedy builds.
  - composer cs
  - composer phpunit
  - composer behat

after_success:
    - if [ $(phpenv version-name) = "7.0" ]; then composer coveralls; fi

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/composer
    - $HOME/.composer/cache

before_deploy:
  - composer phar:install-tools
  - composer install --prefer-dist --no-dev --no-interaction
  - composer phar:build

deploy:
  provider: releases
  api_key:
    secure: LQSoZ2NKrPq+C4Ho1brcSCHKmQ7oWphvZY7wKurcaRm0hE7cTjk7Y3FTb2YaPTgO7mRaK0wQRzfR7iBOcW1vvU+0va0TvahameR8RnN9iI6V1NMJMtasBJoCy2dGlA5Wv1O37A4ueLTgPJHPmnTzFxbnxoEY/lDDOsvP73mKY20=
  file: terminus.phar
  skip_cleanup: true
  on:
    tags: true
    repo: pantheon-systems/terminus
