# https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs
defaults: &defaults
  working_directory: ~/terminus
  docker:
    - image: quay.io/pantheon-public/php-ci:1.x
  environment:
    TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    TERM: dumb

version: 2.1
jobs:
  functional:
    <<: *defaults
    steps:
      - checkout
      # Install without dev components to build a smaller phar
      - run: composer install --no-dev --no-interaction --prefer-dist
      - run: composer phar:install-tools
      - run: composer phar:build
      # Re-install with dev components so that we can run phpunit
      - run: composer install --no-interaction --prefer-dist
      - run: composer functional

workflows:
  version: 2
  terminus:
    jobs:
      - functional
